GET http://localhost:3000/api/v1/students

###

GET http://localhost:3000/api/v1/students/63d02c2cc145c9efc4a41ddd

###

POST http://localhost:3000/api/v1/students
Content-Type: application/json

###

DELETE http://localhost:3000/api/v1/students/63d2bf2ff9069617775e2cb0